
project:
  type: website
  output-dir: docs
  
website:
  title: "Dumb website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pineapple.qmd
      - howtoeatwithchopstick.qmd
    tools:
      - icon: github
        href: https://github.com/LilCoderAsian/LilCoderAsian.github.io
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, LilCoderAsian"

format:
  html:
    theme: sketchy
    toc: true
    css: styles.css

editor: source

